### ISSUE TITLE
support 24x24 and 64x64 sizes

### ISSUE THREAD

**Issue by AshUK** [steambap/png-to-ico#3]
As per [MS Docs](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742485(v=vs.85).aspx) 

> For Classic Mode, the full set is 16x16, 24x24, 32x32, 48x48 and 64x64.

**Comment by steambap** [comment]
For older Windows like XP, not only I have to add 24x24 and 64x64 sizes, I also have to add 8-bit and 4-bit color version of the icon.

Since I don't have any old Windows machine, I want to limit the scope of this project. In other words, this module is more like `png to ico format for Electron apps that run on Windows 10 / Windows 7`.

So as per [MS Docs](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742485(v=vs.85).aspx)

> The full set includes 16x16, 32x32, 48x48, and 256x256
